import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const URGENCY_CONFIG = {
  immediate: { color: 'text-red-400', bg: 'bg-red-950/30 border-red-800', label: 'Immediate Action Required' },
  within_24h: { color: 'text-yellow-400', bg: 'bg-yellow-950/30 border-yellow-800', label: 'Action Within 24 Hours' },
  routine: { color: 'text-emerald-400', bg: 'bg-emerald-950/30 border-emerald-800', label: 'Routine Review' },
};

export default function CivicExport({ civicAction, draft, location, eventType }) {
  const [expanded, setExpanded] = useState(false);
  const [exported, setExported] = useState(false);

  if (!civicAction) return null;

  const urgencyCfg = URGENCY_CONFIG[civicAction.urgency] || URGENCY_CONFIG.routine;

  const handleExport = () => {
    const content = `CIVIC ACTION SUMMARY — Pramaan Verification System
Generated: ${new Date().toLocaleString()}
${'='.repeat(60)}

URGENCY: ${civicAction.urgency?.toUpperCase()}
LOCATION: ${location || 'Unknown'}
EVENT TYPE: ${eventType || 'Unknown'}

SUMMARY:
${civicAction.summary}

DEPARTMENTS TO NOTIFY:
${(civicAction.departments || []).map(d => `• ${d}`).join('\n') || '• None identified'}

SUGGESTED ACTIONS:
${(civicAction.suggested_actions || []).map((a, i) => `${i + 1}. ${a}`).join('\n') || 'None'}

DRAFT BRIEF:
${draft || 'N/A'}

${'='.repeat(60)}
This summary was generated by Pramaan AI verification system.
All information requires editorial review before official action.`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pramaan-civic-action-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setExported(true);
    setTimeout(() => setExported(false), 3000);
  };

  return (
    <div className="glass-card overflow-hidden">
      <button
        onClick={() => setExpanded(e => !e)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-gray-800/30 transition-colors"
      >
        <div className="flex items-center gap-3">
          <span className="text-lg">🏛️</span>
          <div className="text-left">
            <h3 className="text-sm font-semibold text-gray-200">Civic Action Summary</h3>
            <p className="text-xs text-gray-500">{civicAction.action_required ? 'Action required — forward to authorities' : 'No immediate civic action needed'}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {civicAction.action_required && (
            <span className={`px-2 py-0.5 text-xs font-bold rounded border ${urgencyCfg.bg} ${urgencyCfg.color}`}>
              {civicAction.urgency?.toUpperCase()}
            </span>
          )}
          <span className="text-gray-500 text-sm">{expanded ? '▲' : '▼'}</span>
        </div>
      </button>

      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 space-y-4 border-t border-gray-800 pt-4">
              <div className={`p-3 rounded-lg border ${urgencyCfg.bg}`}>
                <p className={`text-xs font-bold mb-1 ${urgencyCfg.color}`}>{urgencyCfg.label}</p>
                <p className="text-sm text-gray-300 leading-relaxed">{civicAction.summary}</p>
              </div>

              {civicAction.departments?.length > 0 && (
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wide mb-2">Departments to Notify</p>
                  <div className="flex flex-wrap gap-2">
                    {civicAction.departments.map((dept, i) => (
                      <span key={i} className="px-2.5 py-1 bg-gray-800 text-gray-300 text-xs rounded-lg border border-gray-700">
                        🏢 {dept}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {civicAction.suggested_actions?.length > 0 && (
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wide mb-2">Suggested Actions</p>
                  <ul className="space-y-1.5">
                    {civicAction.suggested_actions.map((action, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                        <span className="text-blue-500 mt-0.5 flex-shrink-0">{i + 1}.</span>
                        {action}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <button
                onClick={handleExport}
                className="w-full py-2.5 bg-gray-800 hover:bg-gray-700 border border-gray-700 hover:border-gray-600 text-gray-300 text-sm font-medium rounded-lg transition-colors flex items-center justify-center gap-2"
              >
                {exported ? '✓ Downloaded' : '⬇️ Export Civic Report (.txt)'}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
